luci: Xray XHTTP "stream-one" "keepAlivePeriod" and code optimization
Openwrt-Passwall/openwrt-passwall pull request #3542
Opened 2024-11-29 09:41 UTC by lwb1978

等待 xray release

2024-11-29 12:30 UTC, lwb1978 commented
待验证，暂不合并

2024-11-30 06:44 UTC, Pacalini requested changes

2024-11-30 06:44 UTC, Pacalini commented on luci-app-passwall/luasrc/passwall/util_xray.lua
> +						end)() and "stream-up") or (node.xhttp_mode or "auto"),
不用加，具体的兼容性交给 core 判断，填错了就让它正常报错。

2024-11-30 06:44 UTC, Pacalini commented on luci-app-passwall/luasrc/model/cbi/passwall/client/type/ray.lua
> +o = s:option(Value, option_name("xhttp_keepAlivePeriod"), translate("KeepAlivePeriod(second)"))
不用加，用户需要的话填在 extra 里

2024-11-30 07:04 UTC, lwb1978 commented on luci-app-passwall/luasrc/model/cbi/passwall/client/type/ray.lua
> +o = s:option(Value, option_name("xhttp_keepAlivePeriod"), translate("KeepAlivePeriod(second)"))
这样的话util也不用加这个参数吧，我回头再改改

2024-11-30 07:10 UTC, Pacalini commented on luci-app-passwall/luasrc/model/cbi/passwall/client/type/ray.lua
> +o = s:option(Value, option_name("xhttp_keepAlivePeriod"), translate("KeepAlivePeriod(second)"))
> 这样的话util也不用加这个参数吧，我回头再改改

对，XHTTP 除了现在的四个参数，后续加东西 除非涉及防火墙，应该都不用管了

2024-11-30 11:47 UTC, merged